import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

const vazirMatn = Vazirmatn({
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "تکنولایف - فروشگاه اینترنتی موبایل و تکنولوژی",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl" className={`${vazirMatn.className}`}>
            <body>
                {children}
            </body>
        </html>
    );
}
